// <auto-generated />
using System;
using Mathematics.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mathematics.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Mathematics.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth = new DateTime(2003, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ruzimurodabdunazarov@gmail.com",
                            Login = "Ruzimurod03",
                            Name = "Ruzimurod",
                            Password = "P@ssvv0rd",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Birth = new DateTime(1997, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "DilnerHuran@gmail.com",
                            Login = "Hurnur42",
                            Name = "Huranna",
                            Password = "RuzN22s",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Birth = new DateTime(2003, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Niginochka@gmail.com",
                            Login = "Nigi32",
                            Name = "Nigina",
                            Password = "Od4er36g",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
